apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: /config/overrides.properties
          volumeMounts:
            - name: config-volume
              mountPath: /config
    volumes:
      - name: config-volume
        configMap:
          name: spring-hello-config

######################################
    #       volumeMounts:
    #         - name: config-volume
    #           mountPath: /config

    # volumes:
    #   - name: config-volume
    #     configMap:
    #       name: spring-hello-config
# You defined a volume named config-volume sourced from the ConfigMap spring-hello-config.
# You mounted this volume at /config inside the container.
# The container will have access to all files defined in the ConfigMap at /config.