apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-hello-argocd-application
  namespace: argocd
spec:
  project: spring-hello-proj
  source:
    repoURL: 'https://github.com/ssmcse03/spring-hello-argo.git'
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: np-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
