apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ssmcse03/spring-hello-argo.git'
    targetRevision: main
    # path: k8s
    path: spring-hello-chart

    ##ComparisonError Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = error loading repo index: failed to get index: 404 Not Found
    ## Try Solution 1- If you are using a Git repository to store your Helm chart, you should remove the chart field and use the path field to specify the location of the chart in the repository.
    # chart: spring-hello-chart
    # helm:
    #   valueFiles:
    #     - values.yaml
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
